### ISSUE TITLE
Spike: Pipelines-postman

### ISSUE THREAD

**Issue by RandallKeur** [JesseMattson/PurrgentCare#47]
Title: Decide on path forward with implementing Postman in pipelines

Description: Create a design to implement Postman tests/calls in the pipeline. Potential solutions: Newman tests, Postman test suite.

**Comment by RandallKeur** [comment]
Going to need someone with admin rights of the repo to do this in order to run postman in the pipelines.
@JesseMattson  😄 

`
Setting Up Secrets:
Go to your GitHub repository.
Click on Settings.
In the left sidebar, click on Secrets and variables -> Actions.
Click on New repository secret.
Add PERSONS_BASE_URL, PET_BASE_URL, and ACCOUNT_BASE_URL with their respective values.
`

**Comment by JesseMattson** [comment]
Secrets added to repo

**Comment by JesseMattson** [comment]
Closed by #58
