### ISSUE TITLE
Feature: Configure Githug repo secrets

### ISSUE THREAD

**Issue by RandallKeur** [JesseMattson/PurrgentCare#62]
In order to parameterize the Base URLS we leverage in Postman/Newman, we need to setup secrets within the Github repository.
This requires an admin to perform this action and would need to continue to add more Base URLS as we add more to the application.
See more information [here](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-development-environment-secrets-for-your-repository-or-organization)

Task: 
Replace the variables setup [here](https://github.com/JesseMattson/PurrgentCare/pull/58#discussion_r1672128503) by adding these as secrets in the Github repo, then re-factor that work to leverage these secrets instead of hard-coding them in source code.

Deliverable:
Meet Definition of Done and have pipelines pass from new PR.

**Comment by JesseMattson** [comment]
Added URLs as secrets to Repo
