### ISSUE TITLE
Chore: Refactor tests

### ISSUE THREAD

**Issue by RandallKeur** [JesseMattson/PurrgentCare#71]
Description: Refactor tests to encapsulate nested fake data inside Fake Data Generator

Technical Details: 

1. Pull back embedded fake data into the parent object.
- Example: generateAccount(accountId, name, etc.) --> generateAccount(). Under this theory, generateAccount would generate all of its needed attributes within the method as opposed to passing them in to the method itself.
2. Apply setters to Model objects as necessary 
- Example PetId, AccountId, etc.

Acceptance Criteria:
- Refactor all necessary tests
- Meet DoD

Depends on #59 and #69 being completed first.

**Comment by JesseMattson** [comment]
Accomplished by #59, #79, #69 

This issue can be closed after a final walkthrough with the team to determine if any more optimizations are possible.
